language: fr
confirmation_emojis:
    accept: ✅
    cancel: ❌
admin_command_max_duration: 1h
admin_command_powerlevel: 50
default_matrix_perms:
    users_default: 10
    events:
        m.room.name: 100
        m.room.power_levels: 100
        m.room.history_visibility: 100
        m.room.canonical_alias: 50
        m.room.avatar: 50
        m.room.tombstone: 100
        m.room.server_acl: 100
        m.room.encryption: 100
        m.space.child: 50
        m.room.topic: 50
        m.room.pinned_events: 50
        m.reaction: 5
        im.vector.modular.widgets: 50
    events_default: 10
    state_default: 50
    ban: 50
    kick: 50
    redact: 50
    invite: 50
    historical: 100
superusers:
    - "@example:instance.tld"
